### ISSUE TITLE
folder capitalization

### ISSUE THREAD

**Issue by bpffjl** [GSA/msg_project_template#2]
Should  change all folder names to lower case?

**Comment by saraguenther** [comment]
I did notice that everything but data and renv were capitalized. If it's the norm that's fine. Also fine to keep consistent and change to all lower case

**Comment by jwbowers** [comment]
I guess so. That is fine. Took longer than I thought but succeeded using the local linux machines: [a6c8a34](https://github.com/GSA/msg_project_template/commit/a6c8a346d9c7c059b8d9818dcf2888d74245dad2)  So, closing this.
