### ISSUE TITLE
Dealing with data

### ISSUE THREAD

**Issue by bpffjl** [GSA/msg_project_template#7]
I was just looking at this and say the data directory. A while ago we had a discussion about making sure that we keep data in google drive. Should we remove this folder from the directory? 

I wrote some templates for analysis plans, analysis implementation, and data preparation that are part of the [oesrrr package](https://github.com/GSA/oesrrr). Should we bring these over to this template? I mention them here, because they have parameters to access data in google drive.

**Comment by jwbowers** [comment]
I'm happy to remove `data` and adjust the repository `.gitignore` and `README.md` to reflect this. @saraguenther Does this make sense to you?

**Comment by saraguenther** [comment]
@jwbowers @bpffjl I think removing the data folder makes sense in service of clarifying what is expected to live on github and what is expected to live in google drive. The remaining folder I'm curious about is "Documents" -- what should we plan to keep here vs. in google drive? Everything else looks great!

**Comment by jwbowers** [comment]
Removed it here c9b5711   And left it in .gitignore just in case someone makes a `data` directory in the future.
